apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-app
  labels:
    app: pipeline-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-app
  template:
    metadata:
      labels:
        app: pipeline-app
    spec:
      containers:
      - name: pipeline-app
        image: ghcr.io/zackbjd/pipeline:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: ghcr-secret